# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug_win32
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug_win32)
  das_config = debug_win32
  AsciiStreamReaderTest_config = debug_win32
  WavefrontObjParserTest_config = debug_win32
  AsciiSTLParserTest_config = debug_win32
  BinarySTLParserTest_config = debug_win32

else ifeq ($(config),debug_linux)
  das_config = debug_linux
  AsciiStreamReaderTest_config = debug_linux
  WavefrontObjParserTest_config = debug_linux
  AsciiSTLParserTest_config = debug_linux
  BinarySTLParserTest_config = debug_linux

else ifeq ($(config),release_win32)
  das_config = release_win32
  AsciiStreamReaderTest_config = release_win32
  WavefrontObjParserTest_config = release_win32
  AsciiSTLParserTest_config = release_win32
  BinarySTLParserTest_config = release_win32

else ifeq ($(config),release_linux)
  das_config = release_linux
  AsciiStreamReaderTest_config = release_linux
  WavefrontObjParserTest_config = release_linux
  AsciiSTLParserTest_config = release_linux
  BinarySTLParserTest_config = release_linux

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := das AsciiStreamReaderTest WavefrontObjParserTest AsciiSTLParserTest BinarySTLParserTest

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

das:
ifneq (,$(das_config))
	@echo "==== Building das ($(das_config)) ===="
	@${MAKE} --no-print-directory -C . -f das.make config=$(das_config)
endif

AsciiStreamReaderTest: das
ifneq (,$(AsciiStreamReaderTest_config))
	@echo "==== Building AsciiStreamReaderTest ($(AsciiStreamReaderTest_config)) ===="
	@${MAKE} --no-print-directory -C . -f AsciiStreamReaderTest.make config=$(AsciiStreamReaderTest_config)
endif

WavefrontObjParserTest: das
ifneq (,$(WavefrontObjParserTest_config))
	@echo "==== Building WavefrontObjParserTest ($(WavefrontObjParserTest_config)) ===="
	@${MAKE} --no-print-directory -C . -f WavefrontObjParserTest.make config=$(WavefrontObjParserTest_config)
endif

AsciiSTLParserTest: das
ifneq (,$(AsciiSTLParserTest_config))
	@echo "==== Building AsciiSTLParserTest ($(AsciiSTLParserTest_config)) ===="
	@${MAKE} --no-print-directory -C . -f AsciiSTLParserTest.make config=$(AsciiSTLParserTest_config)
endif

BinarySTLParserTest: das
ifneq (,$(BinarySTLParserTest_config))
	@echo "==== Building BinarySTLParserTest ($(BinarySTLParserTest_config)) ===="
	@${MAKE} --no-print-directory -C . -f BinarySTLParserTest.make config=$(BinarySTLParserTest_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f das.make clean
	@${MAKE} --no-print-directory -C . -f AsciiStreamReaderTest.make clean
	@${MAKE} --no-print-directory -C . -f WavefrontObjParserTest.make clean
	@${MAKE} --no-print-directory -C . -f AsciiSTLParserTest.make clean
	@${MAKE} --no-print-directory -C . -f BinarySTLParserTest.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug_win32"
	@echo "  debug_linux"
	@echo "  release_win32"
	@echo "  release_linux"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   das"
	@echo "   AsciiStreamReaderTest"
	@echo "   WavefrontObjParserTest"
	@echo "   AsciiSTLParserTest"
	@echo "   BinarySTLParserTest"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"