#!/bin/sh

DASTOOL_EXEC="../build/debug/DASTool"
WOBJ_PATH="../third_party/3DModelSamples/wobj/*.obj"
WOBJ_OUT_PATH="../dasfiles/obj"

RED='\033[1;31m'
GREEN='\033[1;32m'
NO_COLOR='\033[0m'

# Check if output directories exist
if [[ ! -d "$WOBJ_OUT_PATH" ]]; then
    mkdir -p "$WOBJ_OUT_PATH"
fi

# Convert wobj files
let i=1
printf "${GREEN}-- Converting wobj files --${NO_COLOR}\n"

for f in $WOBJ_PATH; do
    printf "%d. Testing with file '%s'\n" "$i" "$f"
    OUT_NAME="$WOBJ_OUT_PATH/${f##*/}"
    $DASTOOL_EXEC convert "$f" -o "$OUT_NAME" | tail -10 >> stla.log

    # Check if program execution failed
    if [[ "${?}" -ne "0" ]]; then
        printf "${RED}Test nr %d failed!${NO_COLOR}\n" "$i"
    fi
    let i=$i+1
done
